// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DonkeyWork.Persistence.Agent.Migrations
{
    /// <inheritdoc />
    public partial class DropRetriesCount : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Attempts",
                schema: "AgentPersistenceContext",
                table: "ActionExecutions");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "Attempts",
                schema: "AgentPersistenceContext",
                table: "ActionExecutions",
                type: "integer",
                nullable: false,
                defaultValue: 0);
        }
    }
}
