// <auto-generated />
using System;
using System.Collections.Generic;
using DonkeyWork.Chat.Common.Models.Agents.Models;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DonkeyWork.Persistence.Agent.Migrations
{
    /// <inheritdoc />
    public partial class AddAgents : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "ActionModelConfiguration",
                schema: "AgentPersistenceContext",
                table: "Actions",
                newName: "ModelConfiguration");

            migrationBuilder.CreateTable(
                name: "Agents",
                schema: "AgentPersistenceContext",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    UserId = table.Column<Guid>(type: "uuid", nullable: false),
                    Name = table.Column<string>(type: "text", nullable: false),
                    Description = table.Column<string>(type: "text", nullable: false),
                    ExecutionCount = table.Column<int>(type: "integer", nullable: false),
                    Tags = table.Column<List<string>>(type: "jsonb", nullable: false),
                    Nodes = table.Column<List<AgentNode>>(type: "jsonb", nullable: false),
                    NodeEdges = table.Column<List<AgentNodeEdge>>(type: "jsonb", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Agents", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Agents_Name_UserId",
                schema: "AgentPersistenceContext",
                table: "Agents",
                columns: new[] { "Name", "UserId" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Agents",
                schema: "AgentPersistenceContext");

            migrationBuilder.RenameColumn(
                name: "ModelConfiguration",
                schema: "AgentPersistenceContext",
                table: "Actions",
                newName: "ActionModelConfiguration");
        }
    }
}
