// <auto-generated />
using System.Collections.Generic;
using DonkeyWork.Chat.Common.Models.Providers.Tools;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DonkeyWork.Persistence.Agent.Migrations
{
    /// <inheritdoc />
    public partial class ToolsActions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<List<ToolProviderApplicationType>>(
                name: "AllowedTools",
                schema: "AgentPersistenceContext",
                table: "Actions",
                type: "jsonb",
                nullable: false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AllowedTools",
                schema: "AgentPersistenceContext",
                table: "Actions");
        }
    }
}
