services:
  donkeywork-chat-api:
    image: 192.168.0.140:8443/donkeywork-chat-api:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: src/backend/DonkeyWork.Chat.Api/Dockerfile
    networks:
        - donkeywork
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: donkeywork
      POSTGRES_PASSWORD: donkeywork
      POSTGRES_DB: donkeywork
    ports:
      - "5532:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - donkeywork
  donkeywork-chat-ui:
    image: 192.168.0.140:8443/donkeywork-chat-ui:latest
    platform: linux/amd64
    build:
      context: ./src/ui
      dockerfile: Dockerfile
    ports:
      - "8012:8000"
    networks:
      - donkeywork
networks:
  donkeywork:
