// <auto-generated />
using System;
using DonkeyWork.Persistence.Chat;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DonkeyWork.Persistence.Chat.Migrations
{
    [DbContext(typeof(ChatPersistenceContext))]
    partial class ChatPersistenceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ChatPersistenceContext")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DonkeyWork.Persistence.Common.Entity.Base.BaseUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DonkeyWork.Persistence.Chat.Entity.Conversation.ConversationEntity", b =>
                {
                    b.HasBaseType("DonkeyWork.Persistence.Common.Entity.Base.BaseUserEntity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.ToTable("Conversations", "ChatPersistenceContext");
                });

            modelBuilder.Entity("DonkeyWork.Persistence.Chat.Entity.Conversation.ConversationMessageEntity", b =>
                {
                    b.HasBaseType("DonkeyWork.Persistence.Common.Entity.Base.BaseUserEntity");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MessageOwner")
                        .HasColumnType("integer");

                    b.Property<Guid>("MessagePairId")
                        .HasColumnType("uuid");

                    b.HasIndex("ConversationId");

                    b.HasIndex("MessagePairId");

                    b.ToTable("ConversationMessages", "ChatPersistenceContext");
                });

            modelBuilder.Entity("DonkeyWork.Persistence.Chat.Entity.Conversation.ToolCallEntity", b =>
                {
                    b.HasBaseType("DonkeyWork.Persistence.Common.Entity.Base.BaseUserEntity");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessagePairId")
                        .HasColumnType("uuid");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasIndex("ConversationId");

                    b.HasIndex("MessagePairId");

                    b.ToTable("ToolCalls", "ChatPersistenceContext");
                });

            modelBuilder.Entity("DonkeyWork.Persistence.Chat.Entity.Conversation.ConversationMessageEntity", b =>
                {
                    b.HasOne("DonkeyWork.Persistence.Chat.Entity.Conversation.ConversationEntity", "Conversation")
                        .WithMany("MessageEntities")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("DonkeyWork.Persistence.Chat.Entity.Conversation.ToolCallEntity", b =>
                {
                    b.HasOne("DonkeyWork.Persistence.Chat.Entity.Conversation.ConversationEntity", "Conversation")
                        .WithMany("ToolCallEntities")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("DonkeyWork.Persistence.Chat.Entity.Conversation.ConversationEntity", b =>
                {
                    b.Navigation("MessageEntities");

                    b.Navigation("ToolCallEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
